GLOBAL_DEBUG_FLAG = 0
breaker_count = 0

chalk_colors = {
    "BLACK": "\x1b[30m",
    "RED": "\x1b[31m",
    "GREEN": "\x1b[32m",
    "YELLOW": "\x1b[33m",
    "BLUE": "\x1b[34m",
    "RESET": "\x1b[0m",
    "BRIGHT": "\x1b[1m",
    "black": "\x1b[30m",
    "red": "\x1b[31m",
    "green": "\x1b[32m",
    "yellow": "\x1b[33m",
    "blue": "\x1b[34m",
    "reset": "\x1b[0m",
    None: "",
    "": "",
    "bright": "\x1b[1m",
    "bold": "\x1b[1m",
}

file_extensions = [
    "dialogue",
    "note",
    "story",
    "log",
    "typ",
    "md",
    "vimrc",
    "txt",
    "grammar",
    "drafts",
    "js",
    "py",
    "vim",
    "json",
    "css",
    "html",
    "math",
    "history",
    "ts",
    "vue",
    "pdf",
]

filetype_aliases = {
    "js": "javascript",
    "py": "python",
    "md": "markdown",
    "html": "html",
    "css": "css",
    "json": "json",
}

dirdict = {
    "default": "/home/kdog3682/2024",
    "javascript": "/home/kdog3682/2024-javascript/",
    "javascript": "/home/kdog3682/2024-python/",
    "javascript": "/home/kdog3682/2024-writing/",
    "javascript": "/home/kdog3682/2023/",
    "css": "/home/kdog3682/2023/",
    "html": "/home/kdog3682/2023/",
    "downloads": "/mnt/chromeos/MyFiles/Downloads",
    "python": "/home/kdog3682/PYTHON",
    "vim": "/home/kdog3682/.vim/ftplugin",
}

google_scopes = [
    "https://www.googleapis.com/auth/classroom.announcements",
    "https://www.googleapis.com/auth/classroom.courses",
    "https://www.googleapis.com/auth/classroom.coursework.me",
    "https://www.googleapis.com/auth/classroom.coursework.students",
    "https://www.googleapis.com/auth/classroom.courseworkmaterials",
    "https://www.googleapis.com/auth/classroom.guardianlinks.students",
    "https://www.googleapis.com/auth/classroom.profile.emails",
    "https://www.googleapis.com/auth/classroom.profile.photos",
    "https://www.googleapis.com/auth/classroom.push-notifications",
    "https://www.googleapis.com/auth/classroom.rosters",
    "https://www.googleapis.com/auth/classroom.topics",
    "https://www.googleapis.com/auth/cse",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/drive.appdata",
    "https://www.googleapis.com/auth/drive.file",
    "https://www.googleapis.com/auth/drive.metadata",
    "https://www.googleapis.com/auth/drive.scripts",
    "https://www.googleapis.com/auth/gmail.compose",
    "https://www.googleapis.com/auth/gmail.insert",
    "https://www.googleapis.com/auth/gmail.labels",
    "https://www.googleapis.com/auth/gmail.metadata",
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.settings.basic",
    "https://www.googleapis.com/auth/gmail.settings.sharing",
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/youtube.channel-memberships.creator",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtubepartner",
    "https://www.googleapis.com/auth/youtubepartner-channel-audit"
]

git_ignore_patterns = {
    "python": [
        "__pycache__/",
        "*.py[cod]",
        "*$py.class",
        ".pytest_cache/",
        "venv/",
        "env/",
        ".idea/",
        "*.sqlite3",
        "*.ipynb_checkpoints",
    ],
    "java": [
        "target/",
        "bin/",
        "*.log",
        "*.class",
        ".idea/",
        "*.jar",
        "*.war",
    ],
    "javascript": [
        "env.js",
        "package-lock.json",
        "node_modules/",
        "npm-debug.log",
        "dist/",
        ".env",
        "logs",
        "*.log",
        "npm-debug.log*",
        "yarn-debug.log*",
        "yarn-error.log*",
    ],
    "cpp": [
        "*.o",
        "*.obj",
        "*.exe",
        "*.dll",
        "*.so",
        "*.dylib",
        "bin/",
        "obj/",
        ".vscode/",
    ],
    "ruby": [
        "*.gem",
        ".bundle/",
        "log/",
        "tmp/",
        "vendor/bundle/",
        ".env",
        "*.rbc",
        "capybara-*.html",
        ".rspec",
        "/db/*.sqlite3",
        "/db/*.sqlite3-journal",
        "/public/system",
        "/coverage/",
        "spec/tmp*",
        "**.orig",
        "rerun.txt",
        "pickle-email-*.html",
    ],
    "go": [
        "bin/",
        "pkg/",
        "*.o",
        "*.a",
        "*.so",
        "dist/",
        "build/",
        ".env",
        "vendor/",
    ],
}
